<#
.SYNOPSIS
  Generate Terraform HCL + import blocks for an existing AWS API Gateway REST API.

.DESCRIPTION
  Introspects a deployed REST API via the AWS CLI and emits:
    - aws_api_gateway_rest_api
    - aws_api_gateway_authorizer (per authorizer)
    - aws_api_gateway_resource (per non-root path)
    - aws_api_gateway_method (per method on each resource)
    - aws_api_gateway_integration (per method)
    - aws_api_gateway_method_response + aws_api_gateway_integration_response
      (per status code on each method that has them; OPTIONS+MOCK CORS pattern)
    - aws_api_gateway_deployment + aws_api_gateway_stage (per stage)

  Plus the corresponding `import { to = ..., id = ... }` blocks ready to drop
  into imports.tf. After plan -> iterate to zero diff -> apply, remove the
  import blocks per Phase 6 procedure.

  Built during the 2026-05-19 Phase 6 closure session when capturing 3 REST
  APIs (MealPlannerAPI, jaetill-portal-api, CartoAPI) by hand would have taken
  hours. Saved enormous time vs. hand-writing 50+ resources per API.

.PARAMETER ApiId
  The REST API ID (e.g., "e2h43o5aje").

.PARAMETER ResourcePrefix
  Terraform resource-name prefix (e.g., "mp_rest"). All resources are named
  ${ResourcePrefix}_<purpose>.

.PARAMETER ApiName
  Display name (used in a header comment only).

.PARAMETER Region
  AWS region. Defaults to us-east-2.

.PARAMETER AccountId
  AWS account ID. Defaults to 214599503944.

.OUTPUTS
  Hashtable with `.tf` and `.imports` keys. Write to apigw.tf + imports.tf.

.EXAMPLE
  $res = & ./generate-apigw-rest-tf.ps1 -ApiId e2h43o5aje -ResourcePrefix mp_rest -ApiName MealPlannerAPI
  $res.tf      | Out-File terraform/envs/prod/apigw.tf -Encoding utf8
  $res.imports | Out-File terraform/envs/prod/imports.tf -Encoding utf8

.NOTES
  - Lambda permissions are NOT emitted — they vary by sourceArn pattern per
    Lambda. Add them by hand alongside the generated config.
  - The HTTP API variant (apigatewayv2) is much simpler and doesn't need a
    generator. Write those by hand.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $ApiId,
    [Parameter(Mandatory)] [string] $ResourcePrefix,
    [Parameter(Mandatory)] [string] $ApiName,
    [string] $Region = 'us-east-2',
    [string] $AccountId = '214599503944'
)

$tf = @()
$imports = @()

$apiCfg = aws apigateway get-rest-api --rest-api-id $ApiId --query '{Name:name,EndpointType:endpointConfiguration.types[0],ApiKeySource:apiKeySource}' --output json | ConvertFrom-Json

$tf += "# REST API: $ApiName ($ApiId) - generated by scripts/generate-apigw-rest-tf.ps1"
$tf += ""
$tf += "resource ""aws_api_gateway_rest_api"" ""$ResourcePrefix"" {"
$tf += "  name             = ""$($apiCfg.Name)"""
$tf += "  api_key_source   = ""$($apiCfg.ApiKeySource)"""
$tf += "  endpoint_configuration {"
$tf += "    types = [""$($apiCfg.EndpointType)""]"
$tf += "  }"
$tf += "}"
$tf += ""
$imports += "import {"
$imports += "  to = aws_api_gateway_rest_api.$ResourcePrefix"
$imports += "  id = ""$ApiId"""
$imports += "}"
$imports += ""

$auths = aws apigateway get-authorizers --rest-api-id $ApiId --output json | ConvertFrom-Json
$authRefName = $null
foreach ($a in $auths.items) {
    $aRef = ($a.name -replace '[^a-zA-Z0-9]', '_').ToLower()
    $authRefName = "${ResourcePrefix}_$aRef"
    $tf += "resource ""aws_api_gateway_authorizer"" ""$authRefName"" {"
    $tf += "  name            = ""$($a.name)"""
    $tf += "  rest_api_id     = aws_api_gateway_rest_api.$ResourcePrefix.id"
    $tf += "  type            = ""$($a.type)"""
    $tf += "  provider_arns   = [""$($a.providerARNs[0])""]"
    $tf += "  identity_source = ""$($a.identitySource)"""
    $tf += "}"
    $tf += ""
    $imports += "import {"
    $imports += "  to = aws_api_gateway_authorizer.$authRefName"
    $imports += "  id = ""$ApiId/$($a.id)"""
    $imports += "}"
    $imports += ""
}

$resources = aws apigateway get-resources --rest-api-id $ApiId --embed methods --output json | ConvertFrom-Json
foreach ($r in $resources.items) {
    if ($r.path -eq '/') { continue }
    if (-not $r.resourceMethods) { continue }
    $pathName = ($r.path -replace '/', '_' -replace '\{', '' -replace '\}', '' -replace '-', '_').ToLower().TrimStart('_')
    $resRef = "${ResourcePrefix}_$pathName"

    $tf += "resource ""aws_api_gateway_resource"" ""$resRef"" {"
    $tf += "  rest_api_id = aws_api_gateway_rest_api.$ResourcePrefix.id"
    $tf += "  parent_id   = aws_api_gateway_rest_api.$ResourcePrefix.root_resource_id"
    $tf += "  path_part   = ""$($r.pathPart)"""
    $tf += "}"
    $tf += ""
    $imports += "import {"
    $imports += "  to = aws_api_gateway_resource.$resRef"
    $imports += "  id = ""$ApiId/$($r.id)"""
    $imports += "}"
    $imports += ""

    foreach ($methodName in $r.resourceMethods.PSObject.Properties.Name) {
        $m = $r.resourceMethods.$methodName
        $methodRef = "${resRef}_$($methodName.ToLower())"

        $tf += "resource ""aws_api_gateway_method"" ""$methodRef"" {"
        $tf += "  rest_api_id      = aws_api_gateway_rest_api.$ResourcePrefix.id"
        $tf += "  resource_id      = aws_api_gateway_resource.$resRef.id"
        $tf += "  http_method      = ""$methodName"""
        $tf += "  authorization    = ""$($m.authorizationType)"""
        if ($m.authorizerId -and $authRefName) {
            $tf += "  authorizer_id    = aws_api_gateway_authorizer.$authRefName.id"
        }
        $tf += "  api_key_required = $(($m.apiKeyRequired).ToString().ToLower())"
        $tf += "}"
        $tf += ""
        $imports += "import {"
        $imports += "  to = aws_api_gateway_method.$methodRef"
        $imports += "  id = ""$ApiId/$($r.id)/$methodName"""
        $imports += "}"
        $imports += ""

        $i = $m.methodIntegration
        $tf += "resource ""aws_api_gateway_integration"" ""$methodRef"" {"
        $tf += "  rest_api_id          = aws_api_gateway_rest_api.$ResourcePrefix.id"
        $tf += "  resource_id          = aws_api_gateway_resource.$resRef.id"
        $tf += "  http_method          = aws_api_gateway_method.$methodRef.http_method"
        $tf += "  type                 = ""$($i.type)"""
        if ($i.uri) {
            $tf += "  uri                     = ""$($i.uri)"""
            $tf += "  integration_http_method = ""$($i.httpMethod)"""
        }
        $tf += "  passthrough_behavior = ""$($i.passthroughBehavior)"""
        $tf += "  timeout_milliseconds = $($i.timeoutInMillis)"
        $tf += "  cache_namespace      = ""$($i.cacheNamespace)"""
        $tf += "  cache_key_parameters = []"
        if ($i.requestTemplates) {
            $tf += "  request_templates = {"
            foreach ($k in $i.requestTemplates.PSObject.Properties.Name) {
                $val = $i.requestTemplates.$k -replace '"', '\"'
                $tf += "    ""$k"" = ""$val"""
            }
            $tf += "  }"
        }
        $tf += "}"
        $tf += ""
        $imports += "import {"
        $imports += "  to = aws_api_gateway_integration.$methodRef"
        $imports += "  id = ""$ApiId/$($r.id)/$methodName"""
        $imports += "}"
        $imports += ""

        if ($m.methodResponses) {
            foreach ($status in $m.methodResponses.PSObject.Properties.Name) {
                $mr = $m.methodResponses.$status
                $tf += "resource ""aws_api_gateway_method_response"" ""${methodRef}_$status"" {"
                $tf += "  rest_api_id = aws_api_gateway_rest_api.$ResourcePrefix.id"
                $tf += "  resource_id = aws_api_gateway_resource.$resRef.id"
                $tf += "  http_method = aws_api_gateway_method.$methodRef.http_method"
                $tf += "  status_code = ""$status"""
                if ($mr.responseModels) {
                    $tf += "  response_models = {"
                    foreach ($k in $mr.responseModels.PSObject.Properties.Name) {
                        $tf += "    ""$k"" = ""$($mr.responseModels.$k)"""
                    }
                    $tf += "  }"
                }
                if ($mr.responseParameters) {
                    $tf += "  response_parameters = {"
                    foreach ($k in $mr.responseParameters.PSObject.Properties.Name) {
                        $v = $mr.responseParameters.$k.ToString().ToLower()
                        $tf += "    ""$k"" = $v"
                    }
                    $tf += "  }"
                }
                $tf += "}"
                $tf += ""
                $imports += "import {"
                $imports += "  to = aws_api_gateway_method_response.${methodRef}_$status"
                $imports += "  id = ""$ApiId/$($r.id)/$methodName/$status"""
                $imports += "}"
                $imports += ""
            }
        }
        if ($i.integrationResponses) {
            foreach ($status in $i.integrationResponses.PSObject.Properties.Name) {
                $ir = $i.integrationResponses.$status
                $tf += "resource ""aws_api_gateway_integration_response"" ""${methodRef}_$status"" {"
                $tf += "  rest_api_id = aws_api_gateway_rest_api.$ResourcePrefix.id"
                $tf += "  resource_id = aws_api_gateway_resource.$resRef.id"
                $tf += "  http_method = aws_api_gateway_method.$methodRef.http_method"
                $tf += "  status_code = aws_api_gateway_method_response.${methodRef}_$status.status_code"
                if ($ir.responseParameters) {
                    $tf += "  response_parameters = {"
                    foreach ($k in $ir.responseParameters.PSObject.Properties.Name) {
                        $val = $ir.responseParameters.$k -replace '"', '\"'
                        $tf += "    ""$k"" = ""$val"""
                    }
                    $tf += "  }"
                }
                $tf += "  depends_on = [aws_api_gateway_integration.$methodRef]"
                $tf += "}"
                $tf += ""
                $imports += "import {"
                $imports += "  to = aws_api_gateway_integration_response.${methodRef}_$status"
                $imports += "  id = ""$ApiId/$($r.id)/$methodName/$status"""
                $imports += "}"
                $imports += ""
            }
        }
    }
}

$stages = aws apigateway get-stages --rest-api-id $ApiId --output json | ConvertFrom-Json
foreach ($s in $stages.item) {
    $tf += "resource ""aws_api_gateway_deployment"" ""${ResourcePrefix}_$($s.stageName)"" {"
    $tf += "  rest_api_id = aws_api_gateway_rest_api.$ResourcePrefix.id"
    $tf += "  lifecycle {"
    $tf += "    create_before_destroy = true"
    $tf += "    ignore_changes        = [triggers]"
    $tf += "  }"
    $tf += "}"
    $tf += ""
    $imports += "import {"
    $imports += "  to = aws_api_gateway_deployment.${ResourcePrefix}_$($s.stageName)"
    $imports += "  id = ""$ApiId/$($s.deploymentId)"""
    $imports += "}"
    $imports += ""

    $tf += "resource ""aws_api_gateway_stage"" ""${ResourcePrefix}_$($s.stageName)"" {"
    $tf += "  rest_api_id   = aws_api_gateway_rest_api.$ResourcePrefix.id"
    $tf += "  stage_name    = ""$($s.stageName)"""
    $tf += "  deployment_id = aws_api_gateway_deployment.${ResourcePrefix}_$($s.stageName).id"
    $tf += "}"
    $tf += ""
    $imports += "import {"
    $imports += "  to = aws_api_gateway_stage.${ResourcePrefix}_$($s.stageName)"
    $imports += "  id = ""$ApiId/$($s.stageName)"""
    $imports += "}"
    $imports += ""
}

return @{ tf = ($tf -join "`r`n"); imports = ($imports -join "`r`n") }